# htmltest configuration for docs link check
# See https://github.com/wjdp/htmltest for options

IgnoreURLs:
  - "academy.langchain.com"
  - "fonts.googleapis.com"
  - "fonts.gstatic.com"
  - "https://platform.openai.com/account/api-keys"
  - "https://mcp.apify.com/"

